/*
        The following code is automatically generated by YSmart 12.01.
        Author: Rubao Lee, Yuan Yuan    
        Email: yuanyu@cse.ohio-state.edu
*/

package edu.osu.cse.ysmart.tpch21query;
import java.io.IOException;
import java.util.*;
import java.text.*;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.conf.*;
import org.apache.hadoop.io.*;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.Reducer;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.input.FileSplit;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.mapreduce.lib.output.MultipleOutputs;
import org.apache.hadoop.mapreduce.lib.partition.*;


public class tpch21query005 extends Configured implements Tool{

	public static class Map extends  Mapper<Object, Text,IntWritable,Text>{

		private String filename;
		private int filetag = -1;
		public void setup(Context context) throws IOException, InterruptedException {

			int last_index = -1, start_index = -1;
			String path = ((FileSplit)context.getInputSplit()).getPath().toString();
			last_index = path.lastIndexOf('/');
			last_index = last_index - 1;
			start_index = path.lastIndexOf('/',last_index);
			filename = path.substring(start_index+1,last_index+1);
			if(filename.compareTo("LINEITEM")==0){
				filetag = 1;
			}
			if(filename.compareTo("ORDERS")==0){
				filetag = 2;
			}
		}

		public void map(Object key, Text value,Context context) throws IOException,InterruptedException{

			String line = value.toString();
			String[] line_buf= line.split("\\|");
			BitSet dispatch = new BitSet(32);
			if(filetag ==1){

				if(line_buf[12].compareTo(line_buf[11]) > 0 || true || line_buf[12].compareTo(line_buf[11]) > 0){

					if(!(line_buf[12].compareTo(line_buf[11]) > 0))
						dispatch.set( 0 );
					if(!(line_buf[12].compareTo(line_buf[11]) > 0))
						dispatch.set( 2 );
					if(dispatch.isEmpty())
						context.write(new IntWritable(Integer.parseInt(line_buf[0])),new Text(1+"||"+Integer.parseInt(line_buf[0])+ "|" +Integer.parseInt(line_buf[2])+ "|" ));
					else
						context.write(new IntWritable(Integer.parseInt(line_buf[0])),new Text(1+"|"+dispatch.toString()+"|"+Integer.parseInt(line_buf[0])+ "|" +Integer.parseInt(line_buf[2])+ "|" ));
				}
			}

			if(filetag ==2){

				if(line_buf[2].compareTo("F") == 0){

					if(!(line_buf[2].compareTo("F") == 0))
						dispatch.set( 0 );
					if(dispatch.isEmpty())
						context.write(new IntWritable(Integer.parseInt(line_buf[0])),new Text(2+"||"+Integer.parseInt(line_buf[0])+ "|" ));
					else
						context.write(new IntWritable(Integer.parseInt(line_buf[0])),new Text(2+"|"+dispatch.toString()+"|"+Integer.parseInt(line_buf[0])+ "|" ));
				}
			}

		}

	}

	public static class Reduce extends  Reducer<IntWritable,Text,NullWritable,Text>{

		public void reduce(IntWritable key, Iterable<Text> v, Context context) throws IOException,InterruptedException{

			Iterator values = v.iterator();
			ArrayList[] it_output = new ArrayList[3];
			for(int i=0;i<3;i++){
				it_output[i]=new ArrayList();
			}
			String tmp = "";
			ArrayList al_left_0= new ArrayList();
			ArrayList al_right_0= new ArrayList();
			Double[] result_1=new Double[2];
			ArrayList[] d_count_buf_1=new ArrayList[2];
			int al_line_1 = 0;
			for(int i=0;i<2;i++){
				result_1[i] = 0.0;
				d_count_buf_1[i] = new ArrayList();
			}

			Double[] result_2=new Double[2];
			ArrayList[] d_count_buf_2=new ArrayList[2];
			int al_line_2 = 0;
			for(int i=0;i<2;i++){
				result_2[i] = 0.0;
				d_count_buf_2[i] = new ArrayList();
			}

			while(values.hasNext()){
				String line = values.next().toString();
				String dispatch = line.split("\\|")[1];
				tmp = line.substring(2+dispatch.length()+1);
				String[] line_buf= tmp.split("\\|");
				if(line.charAt(0)=='1'&&(dispatch.length()==0 ||dispatch.indexOf("0")==-1))
					al_left_0.add(tmp);
				if(line.charAt(0)=='2'&&(dispatch.length()==0 ||dispatch.indexOf("0")==-1))
					al_right_0.add(tmp);
				if(line.charAt(0) =='1'&& (dispatch.length()==0 ||dispatch.indexOf('1')==-1)){
					if(d_count_buf_1[0].contains(Integer.parseInt(line_buf[1]))==false)
						d_count_buf_1[0].add(Integer.parseInt(line_buf[1]));
					if(al_line_1==0)
						result_1[1]=(double) Integer.parseInt(line_buf[1]);
					else if(result_1[1]>Integer.parseInt(line_buf[1]))
						result_1[1]= (double) Integer.parseInt(line_buf[1]);
					al_line_1++;
				}
				if(line.charAt(0) =='1'&& (dispatch.length()==0 ||dispatch.indexOf('2')==-1)){
					if(d_count_buf_2[0].contains(Integer.parseInt(line_buf[1]))==false)
						d_count_buf_2[0].add(Integer.parseInt(line_buf[1]));
					if(al_line_2==0)
						result_2[1]=(double) Integer.parseInt(line_buf[1]);
					else if(result_2[1]>Integer.parseInt(line_buf[1]))
						result_2[1]= (double) Integer.parseInt(line_buf[1]);
					al_line_2++;
				}
			}
			String[] line_buf = tmp.split("\\|");
			for(int i=0;i<al_left_0.size();i++){
				String[] left_buf_0=((String)al_left_0.get(i)).split("\\|");
				for(int j=0;j<al_right_0.size();j++){
					String[] right_buf_0=((String)al_right_0.get(j)).split("\\|");
					it_output[0].add(Integer.parseInt(left_buf_0[0])+ "|" +Integer.parseInt(left_buf_0[1])+ "|" );
				}
			}
			result_1[0]=(double)d_count_buf_1[0].size();
			if(result_1[0] > 1 || result_1[0] == 1)
				it_output[1].add(Integer.parseInt(line_buf[0]) + "|"+(result_1[0]) + "|"+(result_1[1]) + "|");
			result_2[0]=(double)d_count_buf_2[0].size();
			it_output[2].add(Integer.parseInt(line_buf[0]) + "|"+(result_2[0]) + "|"+(result_2[1]) + "|");
			ArrayList[] jfc_output = new ArrayList[2];
			for(int i=0;i<2;i++){
				jfc_output[i]=new ArrayList();
			}
			for(int i=0;i<it_output[0].size();i++){
				String[] jfc_left_buf_0 = ((String)it_output[0].get(i)).split("\\|");
				for(int j=0;j<it_output[1].size();j++){
					String[] jfc_right_buf_0 = ((String)it_output[1].get(j)).split("\\|");
					if(Double.parseDouble(jfc_right_buf_0[1]) > 1 || Double.parseDouble(jfc_right_buf_0[1]) == 1 && Integer.parseInt(jfc_left_buf_0[1]) != Double.parseDouble(jfc_right_buf_0[2])){
						jfc_output[0].add(Integer.parseInt(jfc_left_buf_0[0])+ "|" +Integer.parseInt(jfc_left_buf_0[1])+ "|" );
					}
				}
			}
			for(int i=0;i<jfc_output[0].size();i++){
				String[] jfc_left_buf_1=((String)jfc_output[0].get(i)).split("\\|");
				if(it_output[2].size()>0){
					for(int j=0;j<it_output[2].size();j++){
						String[] jfc_right_buf_1=((String)it_output[2].get(j)).split("\\|");
						if((jfc_right_buf_1[1].compareTo("null") == 0) || Double.parseDouble(jfc_right_buf_1[1]) == 1 && Integer.parseInt(jfc_left_buf_1[1]) == Double.parseDouble(jfc_right_buf_1[2])){
							jfc_output[1].add(Integer.parseInt(jfc_left_buf_1[1])+ "|" );
						}
					}
				}else{
					if(false || false && false){
						jfc_output[1].add(Integer.parseInt(jfc_left_buf_1[1])+ "|" );
					}
				}
			}
			NullWritable key_op=NullWritable.get();
			for(int i=0;i<jfc_output[1].size();i++){
				String jfc_result = (String)jfc_output[1].get(i);
				context.write(key_op, new Text(jfc_result));
			}
		}

	}

	public int run(String[] args) throws Exception{

		Configuration conf = new Configuration();
		Job job = new Job(conf,"tpch21query005");
		job.setJarByClass(tpch21query005.class);
		job.setMapOutputKeyClass(IntWritable.class);
		job.setMapOutputValueClass(Text.class);
		job.setOutputKeyClass(NullWritable.class);
		job.setOutputValueClass(Text.class);
		job.setMapperClass(Map.class);
		job.setReducerClass(Reduce.class);
		FileInputFormat.addInputPath(job,new Path(args[0]));
		FileOutputFormat.setOutputPath(job, new Path(args[2]));
		FileInputFormat.addInputPath(job,new Path(args[1]));
		FileOutputFormat.setOutputPath(job, new Path(args[2]));
		return (job.waitForCompletion(true) ? 0 : 1);
	}

	public static void main(String[] args) throws Exception {

			int res = ToolRunner.run(new Configuration(), new tpch21query005(), args);
			System.exit(res);
	}

}

